version: '3.2'

services:
  db:
    image: postgres:14
    container_name: db
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  keycloak_2:
    extends:
      file: ./keycloak/service.yml
      service: keycloak
    depends_on:
      - db

  keycloak_1:
    extends:
      file: ./keycloak/service.yml
      service: keycloak
    depends_on:
      - db

  proxy:
    image: nginx:1.21.3
    container_name: proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - keycloak_1
      - keycloak_2
