version: '3.2'

services:
  db:
    image: postgres:14
    container_name: db
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  k1:
    container_name: k1
    extends:
      file: ./services/keycloak/service.yml
      service: keycloak
    depends_on:
      - db

  k2:
    container_name: k2
    extends:
      file: ./services/keycloak/service.yml
      service: keycloak
    depends_on:
      - db

  proxy:
    image: nginx:1.21.3
    container_name: proxy
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
    depends_on:
      - k1
      - k2
