services:
  keycloak:
    image: jboss/keycloak:15.0.2
    ports:
      - 8080:8080
    environment:
      DB_VENDOR: postgres 
      DB_ADDR: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_FRONTEND_URL: http://localhost:8080/auth
