services:
  keycloak:
    image: jboss/keycloak:15.0.2
    # volumes:
    #  - ./themes/base:/opt/jboss/keycloak/themes/base
    #  - ./themes/custom:/opt/jboss/keycloak/themes/custom
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: postgres 
      DB_ADDR: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_FRONTEND_URL: http://localhost:8080/auth
